### ISSUE TITLE
Inspeccion 23/08/2024

### ISSUE THREAD

**Issue by SergioAle210** [Its-Japo/GestorDocumental-FrontEnd#6]
1. Que no acepta símbolos especiales

**Comment by SergioAle210** [comment]
2. Debe de aparecer un mensaje de alerta cuando el usuario está insertando o subiendo un archivo.

**Comment by SergioAle210** [comment]
3. Que no se tiene que eliminar el usuario al que está actualmente logeado.

**Comment by SergioAle210** [comment]
4. Agregar el botón de la página de inicio

**Comment by SergioAle210** [comment]
5. Poder implementar el visualizador de documentos

**Comment by gabrielpaz2003** [comment]
> 1. Que no acepta símbolos especiales

Solventado en la version 2.0.2

![image](https://github.com/user-attachments/assets/d3558c0c-c599-41ff-b0ed-05ba340c2bc3)
![image](https://github.com/user-attachments/assets/fcf2e7cf-4277-4ee3-8d57-f26b2b5a21e7)

**Comment by gabrielpaz2003** [comment]
Todos los issues resueltos
